Character/urls.py
from django.contrib import admin
from django.urls import path

from . views import karakteradmin, karakteradd, karakterupdate, karakterdelete, dashboard, baseadmin, charadmin, charadd, charupdate, chardelete
from . autentikasi import login_form, signup_form

urlpatterns = [
    # Dashboard
    path('', dashboard),
    path('karakter-admin', karakteradmin, name="karakteradmin"),
    path('karakteradd', karakteradd, name="karakteradd"),
    path('karakterupdate/<int:id>/', karakterupdate, name="karakterupdate"),
    path('karakterdelete/<int:id>/', karakterdelete, name="karakterdelete"),
    path('baseadmin', baseadmin, name="baseadmin"),
    path('login', login_form, name="login"),
    path('signup', signup_form, name="signup"),
    path('char-admin', charadmin, name="charadmin"),
    path('char-add', charadd, name="charadd"),
    path('charupdate/<int:id>/', charupdate, name="charupdate"),
    path('chardelete/<int:id>/', chardelete, name="charudelete")
  
]
 

project_iqbal/urls.py
from django.contrib import admin
from django.urls import path, include

#-------------------MEDIA-------------------
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from . views import home,char,contacts,base,blog,detail,karakter, map

urlpatterns = [
    path('admin/', admin.site.urls),

    # tampilan projectku
    path('', home, name='home'),
    path('char', char, name='char'),
    path('contacts', contacts, name= 'contacts'),
    path('base', base, name='base'),
    path('blog', blog, name='blog'),
    path('detail', detail, name='detail'),
    path('karakter', karakter, name='karakter'),
    path('map', map, name='map'),

    # Dashboard App Character
    path('dashboard/', include('Character.urls')),  
]

#-------------------MEDIA-------------------
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

Character/models.py
from django.db import models
from django.core.exceptions import ValidationError


# Models tier
class Karakter(models.Model):
    ROLE_CHOICES = [
        ('Tank', 'Tank'),
        ('Damage', 'Damage'),
        ('Support', 'Support'),
    ]

    TIER_CHOICES = [
        ('S', 'S'),
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),
    ]

    name = models.CharField(max_length=50)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    difficulty = models.IntegerField(blank=True, null=True)
    tier = models.CharField(max_length=1, choices=TIER_CHOICES, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def clean(self):
        if not (1 <= self.difficulty <= 3):
            raise ValidationError({'difficulty': "Difficulty must be between 1 and 3."})

    def __str__(self):
        return self.name
    

# Models karakter
class Hero(models.Model):
    ROLE_CHOICES = [
        ('Tank', 'Tank'),
        ('Damage', 'Damage'),
        ('Support', 'Support'),
    ]

    TIER_CHOICES = [
        ('S', 'S'),
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),   
    ]

    name = models.CharField(max_length=50)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    image = models.ImageField(upload_to='media', blank=True, null=True)
    tier = models.CharField(max_length=1, choices=TIER_CHOICES, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

templates/dashboard/baseadmin.html
{% load static %}
<!DOCTYPE html>
<!--[if IE 8 ]><html class="ie" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
<!--<![endif]-->

<head>
    <!-- Basic Page Needs -->
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <title>Open9 | NFT Marketplace HTML Template</title>

    <meta name="author" content="themesflat.com">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Theme Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'halaman/css/style.css' %}">

    <!-- Reponsive -->
    <link rel="stylesheet" type="text/css" href="{% static 'halaman/css/responsive.css' %}">

    <!-- Favicon and Touch Icons  -->
    <link rel="shortcut icon" href="{% static 'halaman/icon/Favicon.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'halaman/icon/Favicon.png' %}">

</head>

<body class="body dashboard">

    <!-- preload -->
    <div class="preload preload-container">
        <div class="middle">
            <div class="bar bar1"></div>
            <div class="bar bar2"></div>
            <div class="bar bar3"></div>
            <div class="bar bar4"></div>
            <div class="bar bar5"></div>
            <div class="bar bar6"></div>
            <div class="bar bar7"></div>
            <div class="bar bar8"></div>
          </div>
    </div>
    <!-- /preload -->

    
        
    <div id="wrapper">
        <div id="page" class="home-6 flex">
            
            <div class="section-menu-left">
                <div class="box-logo">
                    <a href="index.html"><img src="{% static 'halaman/images/logo/logo.png' %}" alt=""></a>
                </div>
                <div class="connect">
                    <a href="market-wallet.html" id="connectbtn" class="tf-button style-1 type-1 text-center">
                        <span>Wallet connect</span>
                        <i class="icon-wa"></i>
                    </a>
                </div>
                <div class="list-menu over-content">
                    <ul class="menu-content">
                        <li>
                            <a href="{% url 'home' %}"><i class="icon-home-alt"></i> Home</a>
                        </li>
                        <li>
                            <a href="{% url 'karakteradmin' %}"><i class="icon-gem-1"></i> Tier List</a>
                        </li>
                        <li class="has-item">
                            <a class="button-sub-item"><i class="icon-pages"></i> Editor Pages</a>
                            <ul class="sub-item">
                                <li><a href="{% url 'charadmin' %}">Hero</a></li>
                                <li><a href="#">Map</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="list-menu wrap-bottom">
                    <ul class="menu-bottom">
                        <li class="has-item language relative">
                            <a class="button-sub-item"><img src="{% static 'halaman/images/english.png' %}" alt=""> <span>English</span></a>
                            <ul class="sub-item">
                                <li><img src="{% static 'halaman/images/english.png' %}" alt=""> <span>English</span></li>
                                <li><img src="{% static 'halaman/images/english.png' %}" alt=""> <span>japan</span></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"><i class="icon-sign-out-1"></i> Logout</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="wrap-content">

                {% block content %}

                {% endblock %}


                <footer id="footer">
                    <div class="container-fluid">
                        <div class="footer-bottom style-1 items-center">
                            <p>© 2023 OpeN9 - Made By Themesflat</p>
                            <div class="widget-social">
                                <ul class="flex">
                                    <li><a href="#" class="icon-facebook"></a></li>
                                    <li><a href="#" class="icon-twitter"></a></li>
                                    <li><a href="#" class="icon-vt"></a></li>
                                    <li><a href="#" class="icon-tiktok"></a></li>
                                    <li><a href="#" class="icon-youtube"></a></li>
                                </ul>
                            </div>
                            <ul class="flex">
                                <li>
                                    <a href="#">Privacy Policy</a>
                                </li>
                                <li>
                                    <a href="#">Terms of Service</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </footer>

            </div>
            
            <div class="btn-canvas active">
                <div class="canvas">
                    <span></span>
                </div>
            </div>
            
        </div>

    </div>
    <!-- /#wrapper -->

    <div class="tf-mouse tf-mouse-outer"></div>
    <div class="tf-mouse tf-mouse-inner"></div>

    <div class="progress-wrap active-progress">
        <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
        <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" style="transition: stroke-dashoffset 10ms linear 0s; stroke-dasharray: 307.919, 307.919; stroke-dashoffset: 286.138;"></path>
        </svg>
    </div>

    <!-- Javascript -->
    <script src="{% static 'halaman/js/jquery.min.js' %}"></script>
    <script src="{% static 'halaman/js/popper.min.js' %}"></script>
    <script src="{% static 'halaman/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'halaman/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'halaman/js/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'halaman/js/swiper.js' %}"></script>
    <script src="{% static 'halaman/js/count-down.js' %}"></script>
    
    <script src="{% static 'halaman/js/simpleParallax.min.js' %}"></script>
    <script src="{% static 'halaman/js/gsap.js' %}"></script>
    <script src="{% static 'halaman/js/SplitText.js' %}"></script>
    <script src="{% static 'halaman/js/wow.min.js' %}"></script>
    <script src="{% static 'halaman/js/ScrollTrigger.js' %}"></script>
    <script src="{% static 'halaman/js/gsap-animation.js' %}"></script>
    <script src="{% static 'halaman/js/tsparticles.min.js' %}"></script>
    <script src="{% static 'halaman/js/tsparticles.js' %}"></script>
    <script src="{% static 'halaman/js/main.js' %}"></script>

</body>

</html>

templates/dashboard/charadd.html
{%  extends 'dashboard/baseadmin.html' %}
{% load static %}
{% block content %}
<div class="flat-title-page">
    <div class="themesflat-container">
        <div class="row">
            <div class="col-12">
                <h1 class="heading text-center">Tier List</h1>
                <ul class="breadcrumbs flex justify-center">
                    <li class="icon-keyboard_arrow_right">
                        <a href="../halaman/index.html">Home</a>
                    </li>
                    <li>
                        <a href="#">Explore</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="tf-section-2 discover-item loadmore-12-item">
    <div class="themesflat-container">
        
        <div class="product-item item-activity mb-0">
            <h6><div class="column flex items-center">isi dulu</div></h6>
            <i class="icon-keyboard_arrow_down"></i>
           
            <div class="content">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="table-heading">
                        <div class="column">Name</div>
                        <div class="column">Role</div>
                        <div class="column">Image</div>
                        <div class="column">Tier</div>
                        <div class="column">Desc</div>
                      
                        
                    </div>
                    <div class="table-item">
                        <div class="column flex items-center">{{ forms.name }}</div>
                        <div class="column flex items-center">{{ forms.role }}</div>
                        <div class="column flex items-center">{{ forms.image }}</div>
                        
                        <div class="column flex items-center">{{ forms.tier }}</div>
                        <div class="column flex items-center">{{ forms.description }}</div>
                        <div class="widget-pagination">
                            <div class="" id="wallet-header">
                                <a href="../dashboard/charadmin.html" id="connectbtn" class="widget-pagination">
                                    <button>
                                    <span>Tambah</span>
                                </button>
                                </a>
                            </div>
                        </div>
                    </div>
                </form>
               
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/dashboard/charupdate.html
{%  extends 'dashboard/baseadmin.html' %}
{% load static %}
{% block content %}
<div class="flat-title-page">
    <div class="themesflat-container">
        <div class="row">
            <div class="col-12">
                <h1 class="heading text-center">Tier List</h1>
                <ul class="breadcrumbs flex justify-center">
                    <li class="icon-keyboard_arrow_right">
                        <a href="../halaman/index.html">Home</a>
                    </li>
                    <li>
                        <a href="#">Explore</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="tf-section-2 discover-item loadmore-12-item">
    <div class="themesflat-container">
        
        <div class="product-item item-activity mb-0">
            <h6><div class="column flex items-center">isi dulu</div></h6>
            <i class="icon-keyboard_arrow_down"></i>
           
            <div class="content">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="table-heading">
                        <div class="column">Name</div>
                        <div class="column">Role</div>
                        <div class="column">Image</div>
                        <div class="column">Tier</div>
                        <div class="column">Desc</div>
                      
                        
                    </div>
                    <div class="table-item">
                        <div class="column flex items-center">{{ forms.name }}</div>
                        <div class="column flex items-center">{{ forms.role }}</div>
                        <div class="column flex items-center">{{ forms.image }}</div>
                        
                        <div class="column flex items-center">{{ forms.tier }}</div>
                        <div class="column flex items-center">{{ forms.description }}</div>
                        <div class="widget-pagination">
                            <div class="" id="wallet-header">
                                <a href="../dashboard/charadmin.html" id="connectbtn" class="widget-pagination">
                                    <button>
                                    <span>Tambah</span>
                                </button>
                                </a>
                            </div>
                        </div>
                    </div>
                </form>
               
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/dashboard/karakteradd.html
{%  extends 'dashboard/baseadmin.html' %}
{% load static %}
{% block content %}
<div class="flat-title-page">
    <div class="themesflat-container">
        <div class="row">
            <div class="col-12">
                <h1 class="heading text-center">Tier List</h1>
                <ul class="breadcrumbs flex justify-center">
                    <li class="icon-keyboard_arrow_right">
                        <a href="../halaman/index.html">Home</a>
                    </li>
                    <li>
                        <a href="#">Explore</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="tf-section-2 discover-item loadmore-12-item">
    <div class="themesflat-container">
        
        <div class="product-item item-activity mb-0">
            <h6><div class="column flex items-center">isi dulu</div></h6>
            <i class="icon-keyboard_arrow_down"></i>
           
            <div class="content">
                <form method="post">
                    {% csrf_token %}
                    <div class="table-heading">
                        <div class="column">Name</div>
                        <div class="column">Role</div>
                        <div class="column">Difficulty</div>
                        <div class="column">Description</div>
                      
                        
                    </div>
                    <div class="table-item">
                        <div class="column flex items-center"><input type="text" name="name" class="TextField" maxlength="50" required id="id_name" ></text></div>
                        <div class="column flex items-center">
                            <select name="role" id="id_role">
                                <option value selected>pilih role</option>
                                <option value="Tank">Tank</option>
                                <option value="Damage">Damage</option>
                                <option value="Support">Support</option>
                            </select>
                        </div>
                        <div class="column flex items-center"><span class="tf-color"><input type="number" name="difficulty" class="IntegerField" required id="id_difficulty" ></label></div>
                        <div class="column flex items-center">
                            <select name="tier" id="id_tier">
                                <option value selected>pilih role</option>
                                <option value="S">S</option>
                                <option value="A">A</option>
                                <option value="B">B</option>
                                <option value="C">C</option>
                                <option value="D">D</option>
                            </select>
                        </div>
                        <div class="widget-pagination">
                            <div class="" id="wallet-header">
                                <a href="../halaman/karakter.html" id="connectbtn" class="widget-pagination">
                                    <button>
                                    <span>Tambah</span>
                                </button>
                                </a>
                            </div>
                        </div>
                    </div>
                </form>
               
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/dashboard/karakteradmin.html
{%  extends 'dashboard/baseadmin.html' %}
{% load static %}
{% block content %}
    <div class="flat-title-page">
        <div class="themesflat-container">
            <div class="row">
                <div class="col-12">
                    <h1 class="heading text-center">Tier List</h1>
                    <ul class="breadcrumbs flex justify-center">
                        <li class="icon-keyboard_arrow_right">
                            <a href="index.html">Home</a>
                        </li>
                        <li>
                            <a href="#">Explore</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="tf-section-2 discover-item loadmore-12-item">
        <div class="themesflat-container">

            <div class="product-item item-activity mb-0">
                <h6>
                    <div class="column flex items-center">
                        <div class="widget-pagination">
                            <ul class="justify-center">
                                <li>
                                    <a href="{% url 'karakteradd' %}">+</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </h6>
                <i class="icon-keyboard_arrow_down"></i>
                <div class="content">
                    <div class="table-heading">
                        <div class="column">Name</div>
                        <div class="column">Role</div>
                        <div class="column">Difficulty</div>
                        <div class="column">Description</div>
                        <div class="column">Action</div>

                    </div>
                    {% for karakter in karakter %}
                        <div class="table-item">

                            <div class="column flex items-center">{{ karakter.name }}</div>
                            <div class="column flex items-center">{{ karakter.role|default:"-" }}</div>
                            <div class="column flex items-center"><span
                                    class="tf-color">{{ karakter.difficulty|default:"-" }}</span></div>
                            <div class="column flex items-center"><span
                                    class="tf-color">{{ karakter.tier|default:"-" }}</span></div>
                            <div class="column flex items-center" id="wallet-header">
                                <a href="{% url 'karakterdelete' karakter.id %}" id="connectbtn"
                                   class="widget-pagination mr-2">
                                    <button>
                                        <span>Hapus</span>
                                    </button>
                                </a>
                                <a href="{% url 'karakterupdate' karakter.id %}" id="connectbtn"
                                   class="widget-pagination">
                                    <button>
                                        <span>Update</span>
                                    </button>
                                </a>
                            </div>

                        </div>
                        {% empty %}
                        <p>Tidak ada karakter yang tersedia.</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/dashboard/karakterupdate.html
{%  extends 'dashboard/baseadmin.html' %}
{% load static %}
{% block content %}
            <div class="flat-title-page">
                <div class="themesflat-container">
                    <div class="row">
                        <div class="col-12">
                            <h1 class="heading text-center">Tier List</h1>
                            <ul class="breadcrumbs flex justify-center">
                                <li class="icon-keyboard_arrow_right">
                                    <a href="../halaman/index.html">Home</a>
                                </li>
                                <li>
                                    <a href="#">Explore</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="tf-section-2 discover-item loadmore-12-item">
                <div class="themesflat-container">
                    
                    <div class="product-item item-activity mb-0">
                        <h6><div class="column flex items-center">isi dulu</div></h6>
                        <i class="icon-keyboard_arrow_down"></i>
                       
                        <div class="content">
                            <form method="post">
                                {% csrf_token %}
                                <div class="table-heading">
                                    <div class="column">Name</div>
                                    <div class="column">Role</div>
                                    <div class="column">Difficulty</div>
                                    <div class="column">Description</div>
                                  
                                    
                                </div>
                                <div class="table-item">
                                    <div class="column flex items-center"><input type="text" name="name" class="TextField" maxlength="50" required id="id_name" ></text></div>
                                    <div class="column flex items-center">
                                        <select name="role" id="id_role">
                                            <option value selected>pilih role</option>
                                            <option value="Tank">Tank</option>
                                            <option value="Damage">Damage</option>
                                            <option value="Support">Support</option>
                                        </select>
                                    </div>
                                    <div class="column flex items-center"><span class="tf-color"><input type="number" name="difficulty" class="IntegerField" required id="id_difficulty" ></label></div>
                                        <div class="column flex items-center">
                                            <select name="tier" id="id_tier">
                                                <option value selected>pilih role</option>
                                                <option value="S">S</option>
                                                <option value="A">A</option>
                                                <option value="B">B</option>
                                                <option value="C">C</option>
                                                <option value="D">D</option>
                                            </select>
                                        </div>
                                    <div class="widget-pagination">
                                        <div class="" id="wallet-header">
                                            <a href="../halaman/karakter.html" id="connectbtn" class="widget-pagination">
                                                <button>
                                                <span>Tambah</span>
                                            </button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                           
                        </div>
                    </div>
                </div>
            </div>
{% endblock %}

          

templates/dashboard/login.html
{%  extends 'halaman/base.html' %}
{% load static %}
{% block content %}

            <div class="tf-section-2 pt-60 widget-box-icon">
                <div class="themesflat-container w920">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="heading-section-1">
                                <h2 class="tf-title pb-16">Login</h2>
                                <p class="pb-40">Get started today by entering just a few details</p>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="widget-login">
                                <form id="commentform" class="comment-form" method="POST">
                                    {% csrf_token %}
                                    <p class="pb-40">{{ pesan }}</p>
                                    <fieldset class="username">
                                        <label>Username *</label>
                                        <input type="username" id="username" placeholder="Username Anda" name="username" tabindex="2" value="" aria-required="true" required>
                                    </fieldset>
                                    <fieldset class="password">
                                        <label>Password *</label>
                                        <input class="password-input" type="password" id="password" placeholder="Min. 8 character" name="password" tabindex="2" value="" aria-required="true" required>
                                        <i class="icon-show password-addon" id="password-addon"></i>
                                        <div class="forget-password">
                                            <a href="#">Forget password</a>
                                        </div>
                                    </fieldset>
                                    <div class="btn-submit mb-30">
                                        <button href="{% url 'karakteradd' %}" class="tf-button style-1 h50 w-100" type="submit">Login<i class="icon-arrow-up-right2"></i></button>
                                    </div>
                                </form>    
                                <div class="no-account">Ingin Registrasi <a href="{% url 'signup' %}" class="tf-color">Sign up</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
{% endblock %}